### Test entity
GET localhost:4444/api/test
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW4iLCJleHAiOjE2NzI4MTcyNDcsImlhdCI6MTY3Mjc4MTI0Nywic2NvcGUiOiJST0xFX1VTRVIgUk9MRV9BRE1JTiJ9.r_GXN5UaiVhJYwFcsIiSe0ZELM_x-M8C4iaxl_isKDPxK_crb8MwkhYTCaX9459MpuHWddKxIXX13UfgKYyIdPF5PbQLs0ww0arHEWJQrkwt1mTPBDSF0GeAxun1u18x4tz6Ahzydt4O3p_rVee2hbaO_7nreGsaZ93kNG3cxhPdkc7Jxbg7lTia8tHeCmSLIPn47cPYeAPTSCHs_A5NbC7eLVBBRcpj479sLBZFyvPrqzywb7WuYsx_Nv-xbA8xPqzWlG0ncBkLkocvSgkMFjeW5sGDt2w5z7hxO3XdlPg1eTGV1cePTj4STGqJwHLRBulQOeqVs2U7xhYmSKDVpw


### Hello
GET localhost:4444/hello
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW4iLCJleHAiOjE2NzI4MTcyNDcsImlhdCI6MTY3Mjc4MTI0Nywic2NvcGUiOiJST0xFX1VTRVIgUk9MRV9BRE1JTiJ9.r_GXN5UaiVhJYwFcsIiSe0ZELM_x-M8C4iaxl_isKDPxK_crb8MwkhYTCaX9459MpuHWddKxIXX13UfgKYyIdPF5PbQLs0ww0arHEWJQrkwt1mTPBDSF0GeAxun1u18x4tz6Ahzydt4O3p_rVee2hbaO_7nreGsaZ93kNG3cxhPdkc7Jxbg7lTia8tHeCmSLIPn47cPYeAPTSCHs_A5NbC7eLVBBRcpj479sLBZFyvPrqzywb7WuYsx_Nv-xbA8xPqzWlG0ncBkLkocvSgkMFjeW5sGDt2w5z7hxO3XdlPg1eTGV1cePTj4STGqJwHLRBulQOeqVs2U7xhYmSKDVpw

### Users
GET localhost:4444/api/user
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW4iLCJleHAiOjE2NzI4MTcyNDcsImlhdCI6MTY3Mjc4MTI0Nywic2NvcGUiOiJST0xFX1VTRVIgUk9MRV9BRE1JTiJ9.r_GXN5UaiVhJYwFcsIiSe0ZELM_x-M8C4iaxl_isKDPxK_crb8MwkhYTCaX9459MpuHWddKxIXX13UfgKYyIdPF5PbQLs0ww0arHEWJQrkwt1mTPBDSF0GeAxun1u18x4tz6Ahzydt4O3p_rVee2hbaO_7nreGsaZ93kNG3cxhPdkc7Jxbg7lTia8tHeCmSLIPn47cPYeAPTSCHs_A5NbC7eLVBBRcpj479sLBZFyvPrqzywb7WuYsx_Nv-xbA8xPqzWlG0ncBkLkocvSgkMFjeW5sGDt2w5z7hxO3XdlPg1eTGV1cePTj4STGqJwHLRBulQOeqVs2U7xhYmSKDVpw

### Roles
GET localhost:4444/api/role
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJzZWxmIiwic3ViIjoiYWRtaW4iLCJleHAiOjE2NzI4MTcyNDcsImlhdCI6MTY3Mjc4MTI0Nywic2NvcGUiOiJST0xFX1VTRVIgUk9MRV9BRE1JTiJ9.r_GXN5UaiVhJYwFcsIiSe0ZELM_x-M8C4iaxl_isKDPxK_crb8MwkhYTCaX9459MpuHWddKxIXX13UfgKYyIdPF5PbQLs0ww0arHEWJQrkwt1mTPBDSF0GeAxun1u18x4tz6Ahzydt4O3p_rVee2hbaO_7nreGsaZ93kNG3cxhPdkc7Jxbg7lTia8tHeCmSLIPn47cPYeAPTSCHs_A5NbC7eLVBBRcpj479sLBZFyvPrqzywb7WuYsx_Nv-xbA8xPqzWlG0ncBkLkocvSgkMFjeW5sGDt2w5z7hxO3XdlPg1eTGV1cePTj4STGqJwHLRBulQOeqVs2U7xhYmSKDVpw


### Login

POST localhost:4444/token
# User
# Authorization: Basic c2FtcGxldXNlcjpwYXNzd29yZA==
# Admin
Authorization: Basic YWRtaW46cGFzc3dvcmQ=
